spring:
  application:
    name: projectmanager
  datasource:
    url: jdbc:postgresql://localhost:5432/project_db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


